### ISSUE TITLE
Unable to subscribe to messages

### ISSUE THREAD

**Issue by ShashidharB1996** [rebus-org/Rebus.AmazonSQS#42] opened 2023-01-31 16:13 UTC
Hi

I want to migrate message queue from sql server to SQS.

`
_activator = new BuiltinHandlerActivator();
_activator.Register(() => new Example.ExampleHandler(_activator.Bus));
Configure.With(_activator)
.Transport(x => x.UseAmazonSQS(SqsAcessKey, SqsSecretKey, RegionEndpoint, queueName))
.Routing(r => r.TypeBased().MapAssemblyOf(queueName))
.Subscriptions(t => t.StoreInSqlServer(ConnectionString, "Subscriptions", isCentralized: true))
.Options(b =>
{
b.SimpleRetryStrategy(
errorQueueAddress: $"{queueName}_Errors",
maxDeliveryAttempts: 1,
secondLevelRetriesEnabled: true);
b.SetNumberOfWorkers(2);
b.SetMaxParallelism(2);
})
.Start();

Bus.Subscribe().Wait();

`

This piece of code isn't working, It throws an exception at the line Bus.Subscribe().Wait(); "unable to access queue" and I dont want to use a centralized Subscription storage which should be sql server. So, I changed the transport to

`
_activator = new BuiltinHandlerActivator();
_activator.Register(() => new Example.ExampleHandler(_activator.Bus));
Configure.With(_activator)
.Transport(t => t.UseAmazonSnsAndSqs(
amazonCredentialsFactory: awsCredentials,
amazonSqsConfig: SQSConfig,
amazonSimpleNotificationServiceConfig: SNSConfig,
workerQueueAddress: queueName))
.Routing(r => r.TypeBased().Map(queueName))
.Options(b =>
{
b.SimpleRetryStrategy(
errorQueueAddress: $"{queueName}_Errors",
maxDeliveryAttempts: 1,
secondLevelRetriesEnabled: true);
b.SetNumberOfWorkers(2);
b.SetMaxParallelism(2);
})
.Start();

Bus.Subscribe().Wait();

`
This also throws an exception at the line Bus.Subscribe().Wait(); "unable to access queue".

And I'm publishing messages like this.

`
public IBus GetMessageBusForPublish(string connectionString)
{
if (_messageBus == null)
{
using (var activator = new BuiltinHandlerActivator())
{

                Configure.With(activator)
                    .Transport(x => x.UseAmazonSQSAsOneWayClient(accessKey, secretKey, RegionEndpoint))
                    .Start();

                _messageBus = activator.Bus;
            }
        }
        return _messageBus;
    }
`

I am not getting what I'm doing wrong. Please do help.

**Comment by mookid8000** [comment] 2023-02-01 08:13
Duplicate of https://github.com/rebus-org/Rebus/issues/1075

**Closed by mookid8000** 2023-02-01 08:13 UTC
